# Workflow to automatically deploy shiny application

name: ShinyApp_Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-shiny:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        
      - name: Setup dependencies
        run: |
          install.packages(c("shiny", "rsconnect"), type = "binary")
        shell: Rscript {0}
        
      - name: Push to shiny.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='kailewis', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appName = 'InteractiveCOVIDmap')"
