# Workflow to automatically deploy shiny application

name: ShinyApp_Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-shiny:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        
      - name: Setup dependencies
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore(prompt=FALSE)'
        shell: Rscript {0}
          
      - name: Push to shiny.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name= ${{ env.SHINY_APP_ACC == 'kailewis'}}, token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appName = ${{ env.MASTER_NAME == 'InteractiveCOVIDmap'}})"
        shell: Rscript {0}
