# Workflow to automatically deploy shiny application

name: ShinyApp_Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-shiny:
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        
      - name: Install renv
        run: |
          install.packages("renv")
        shell: Rscript {0}
      
      - name: Restore environment
        run: |
          renv::consent(TRUE)
          renv::restore()
        shell: Rscript {0}
      
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/Library/Application Support/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
            
      - name: Push to shiny.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='kailewis', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appName = 'InteractiveCOVIDmap')"
